name=input("이름을 입력하세요: ")
number=input("학번을 입력하세요: ")
name2=input("학과를 입력하세요: ")
name3=(input("학교를 입력하세요: "))
print("\n<출력>\n이름은: "+name)
print("학번은: "+number)
print("학과는: "+name2)
print("학교는: "+name3)
